/**
 * Oracle tests for the LaTeX log parser. Every fixture in ./fixtures was generated by this
 * project: a document with a known injected defect compiled by TeX Live 2025 pdflatex with
 * -interaction=nonstopmode -no-shell-escape (plus -file-line-error for the *-fle variants).
 * Expected values were read off the raw logs by hand.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseAndEnrichLatexLog, parseLatexLog } from '../../../../src/lib/latex-log';
import { consumeFilePath } from '../../../../src/lib/latex-log/parser';
import { LogScanner } from '../../../../src/lib/latex-log/scanner';

const fixture = (name: string) => readFileSync(join(__dirname, 'fixtures', `${name}.log`), 'utf8');

describe('LogScanner (max_print_line unwrapping)', () => {
	it('rejoins a line wrapped at exactly 79 chars', () => {
		const long = 'a'.repeat(79);
		const s = new LogScanner(`${long}\ncontinued`);
		expect(s.next()).toBe(long + 'continued');
	});
	it('does not join when the next line is a new error', () => {
		const long = 'a'.repeat(79);
		const s = new LogScanner(`${long}\n! Undefined control sequence.`);
		expect(s.next()).toBe(long);
		expect(s.next()).toBe('! Undefined control sequence.');
	});
	it('does not join after a "..." elision', () => {
		const long = 'a'.repeat(76) + '...';
		const s = new LogScanner(`${long}\nnext`);
		expect(s.next()).toBe(long);
	});
	it('handles chained wraps (79+79+rest)', () => {
		const a = 'x'.repeat(79);
		const b = 'y'.repeat(79);
		const s = new LogScanner(`${a}\n${b}\ntail`);
		expect(s.next()).toBe(a + b + 'tail');
	});
});

describe('consumeFilePath', () => {
	it('reads a plain relative path', () => {
		expect(consumeFilePath('./sections/intro.tex) next')?.path).toBe('./sections/intro.tex');
	});
	it('reads a path with spaces in directories and filename', () => {
		expect(consumeFilePath('./a b/c d/weird file.tex')?.path).toBe('./a b/c d/weird file.tex');
	});
	it('reads an absolute Windows path', () => {
		expect(consumeFilePath('c:/texlive/2025/texmf-dist/tex/latex/base/article.cls')?.path).toBe(
			'c:/texlive/2025/texmf-dist/tex/latex/base/article.cls'
		);
	});
	it('rejects prose parentheses', () => {
		expect(consumeFilePath('see the transcript file)')).toBeNull();
		expect(consumeFilePath('badness 10000) something')).toBeNull();
	});
});

describe('parseLatexLog on generated fixtures', () => {
	it('undefined-cs: two distinct errors, file from the paren stack, lines from l.NN', () => {
		const r = parseLatexLog(fixture('undefined-cs'));
		expect(r.errors.map((e) => [e.message, e.file, e.line])).toEqual([
			['Undefined control sequence.', './main.tex', 3],
			['Undefined control sequence.', './main.tex', 7]
		]);
		expect(r.status.fatal).toBe(false);
		expect(r.status.pages).toBe(1);
	});

	it('undefined-cs-fle: file and line from the file:line: prefix', () => {
		const r = parseLatexLog(fixture('undefined-cs-fle'));
		expect(r.errors.map((e) => [e.message, e.file, e.line])).toEqual([
			['Undefined control sequence.', './main.tex', 3],
			['Undefined control sequence.', './main.tex', 7]
		]);
	});

	it('missing-dollar: error recognized with context command', () => {
		const r = parseAndEnrichLatexLog(fixture('missing-dollar'));
		expect(r.errors.length).toBeGreaterThanOrEqual(1);
		expect(r.errors[0].message).toBe('Missing $ inserted.');
		expect(r.errors[0].ruleId).toBe('missing-dollar');
		expect(r.errors[0].line).toBe(3);
	});

	it('env-undefined: align without amsmath gets the package hint', () => {
		const r = parseAndEnrichLatexLog(fixture('env-undefined'));
		const e = r.errors.find((x) => x.ruleId === 'environment-undefined');
		expect(e).toBeDefined();
		expect(e!.hint).toContain('amsmath');
		expect(e!.suggestedPackage).toBe('amsmath');
	});

	it('env-mismatch: begin/end mismatch recognized', () => {
		const r = parseAndEnrichLatexLog(fixture('env-mismatch'));
		const e = r.errors.find((x) => x.ruleId === 'env-mismatch');
		expect(e).toBeDefined();
		expect(e!.message).toContain('\\begin{itemize} on input line 3 ended by \\end{enumerate}');
	});

	it('runaway: runaway prelude + file-ended + emergency stop, fatal status', () => {
		const r = parseLatexLog(fixture('runaway'));
		const messages = r.errors.map((e) => e.message);
		expect(messages.some((m) => m.startsWith('Runaway argument?'))).toBe(true);
		expect(messages.some((m) => m.startsWith('File ended while scanning use of \\textbf'))).toBe(true);
		expect(r.status.emergencyStop).toBe(true);
		expect(r.status.fatal).toBe(true);
		expect(r.status.pages).toBeUndefined();
	});

	it('missing-file: LaTeX Error File not found, attributed to main.tex', () => {
		const r = parseAndEnrichLatexLog(fixture('missing-file'));
		const e = r.errors.find((x) => x.ruleId === 'file-not-found');
		expect(e).toBeDefined();
		expect(e!.message).toContain("File `does-not-exist.tex' not found");
		expect(e!.file).toBe('./main.tex');
	});

	it('stray-amp: misplaced alignment tab', () => {
		const r = parseAndEnrichLatexLog(fixture('stray-amp'));
		expect(r.errors[0].ruleId).toBe('misplaced-alignment-tab');
		expect(r.errors[0].line).toBe(3);
	});

	it('badbox: overfull range + underfull single line, as badboxes not errors', () => {
		const r = parseLatexLog(fixture('badbox'));
		expect(r.errors).toEqual([]);
		expect(r.badboxes.map((b) => [b.line, b.lineEnd ?? null])).toEqual([
			[3, 4],
			[5, null]
		]);
		expect(r.badboxes[0].message).toContain('Overfull \\hbox (44.41731pt too wide)');
		expect(r.badboxes[1].message).toContain('Underfull \\hbox (badness 10000)');
	});

	it('warnings: undefined ref/cite with line numbers, wrapped package warning reassembled', () => {
		const r = parseAndEnrichLatexLog(fixture('warnings'));
		const ref = r.warnings.find((w) => w.ruleId === 'undefined-reference');
		expect(ref).toBeDefined();
		expect(ref!.line).toBe(4); // the "4." was wrapped onto its own physical line
		const cite = r.warnings.find((w) => w.ruleId === 'undefined-citation');
		expect(cite?.line).toBe(4);
		const demo = r.warnings.find((w) => w.message.includes('demopkg'));
		expect(demo).toBeDefined();
		// wrapped + \MessageBreak continuation folded into one message
		expect(demo!.message).toContain('hard-wrapped by the engine');
		expect(demo!.message).toContain('explicit message break');
		// cascade: the "There were undefined references." summary is dropped
		expect(r.warnings.some((w) => w.ruleId === 'undefined-references-summary')).toBe(false);
	});

	it('multifile: errors attributed through the paren stack, spaces in paths survive', () => {
		const r = parseLatexLog(fixture('multifile'));
		expect(r.errors.map((e) => [e.file, e.line])).toEqual([
			['./a b/c d/weird file.tex', 2],
			['./sections/outro.tex', 1]
		]);
	});

	it('multifile-fle: same attribution from file:line prefixes', () => {
		const r = parseLatexLog(fixture('multifile-fle'));
		expect(r.errors.map((e) => [e.file, e.line])).toEqual([
			['./a b/c d/weird file.tex', 2],
			['./sections/outro.tex', 1]
		]);
	});

	it('paper-inject: real multi-file arXiv paper, both injected errors found in the right files', () => {
		const r = parseLatexLog(fixture('paper-inject'));
		const files = r.errors.map((e) => e.file);
		expect(files).toContain('./model_architecture.tex');
		expect(files).toContain('./training.tex');
		const inj = r.errors.find((e) => e.file === './model_architecture.tex');
		expect(inj?.line).toBe(1);
	});

	it('paper-inject-fle: identical attribution via file:line', () => {
		const r = parseLatexLog(fixture('paper-inject-fle'));
		const inj = r.errors.filter((e) => e.file === './model_architecture.tex' || e.file === './training.tex');
		expect(inj.length).toBeGreaterThanOrEqual(2);
	});

	it('never throws on truncated input (robustness)', () => {
		const full = fixture('runaway');
		for (const cut of [0, 10, 100, 500, full.length - 5]) {
			expect(() => parseAndEnrichLatexLog(full.slice(0, cut))).not.toThrow();
		}
	});
});

describe('corpus-sweep catches (July 2026)', () => {
	it('hints the kernel "Invalid UTF-8 byte" error', () => {
		const r = parseAndEnrichLatexLog('! LaTeX Error: Invalid UTF-8 byte "95.\nl.18411 x\n');
		expect(r.errors[0]?.ruleId).toBe('unicode-char');
	});

	it('hints the pdftex.def missing-figure error, with the epstopdf case called out', () => {
		const eps = parseAndEnrichLatexLog(
			"! Package pdftex.def Error: File `fig-eps-converted-to.pdf' not found: using draft setting.\nl.60 x\n"
		);
		expect(eps.errors[0]?.ruleId).toBe('graphics-file-not-found');
		expect(eps.errors[0]?.hint).toContain('shell escape');
		const plain = parseAndEnrichLatexLog("! Package pdftex.def Error: File `figs/model.png' not found: using draft setting.\nl.60 x\n");
		expect(plain.errors[0]?.hint).toContain('figs/model.png');
	});
});

describe('LaTeX Workshop parity additions', () => {
	it('surfaces "No pages of output." as an error, not just status', () => {
		const r = parseLatexLog('No pages of output.\nTranscript written on main.log.');
		expect(r.status.noPages).toBe(true);
		expect(r.errors.map((e) => e.message)).toContain('No pages of output.');
	});

	it('recognizes a bare file:line error (MikTeX -file-line-error)', () => {
		const r = parseLatexLog('chapter1.tex:5: Undefined control sequence.\nl.5 \\foo');
		expect(r.errors[0]?.file).toBe('chapter1.tex');
		expect(r.errors[0]?.line).toBe(5);
	});

	it('tracks MikTeX bare-name file opens on the paren stack', () => {
		const r = parseLatexLog('(natbib.sty\n! Some error.\nl.3 x\n');
		expect(r.errors[0]?.file).toBe('natbib.sty');
	});

	it('skips "ignored error" engine notes', () => {
		const r = parseLatexLog('! Some ignored error follows.');
		expect(r.errors).toHaveLength(0);
	});

	it('captures pdfTeX driver warnings (which LW drops)', () => {
		const r = parseLatexLog('pdfTeX warning (dest): name{fig:x} has been referenced but does not exist');
		expect(r.warnings[0]?.message).toMatch(/^pdfTeX warning/);
	});

	it('extracts column + anchor text from the l.NN context', () => {
		const r = parseLatexLog('! Undefined control sequence.\nl.12 A line \\badmacro\n');
		expect(r.errors[0]?.line).toBe(12);
		expect(r.errors[0]?.column).toBe('A line \\badmacro'.length + 1);
		expect(r.errors[0]?.anchorText).toBe('A line \\badmacro');
	});

	it('strips the redundant "on input line N" from folded warnings but keeps the line', () => {
		const r = parseLatexLog("LaTeX Warning: Reference `fig:x' on page 2 undefined on input line 40.\n");
		expect(r.warnings[0]?.line).toBe(40);
		expect(r.warnings[0]?.message).not.toMatch(/on input line/);
	});

	it('attributes shipout-time boxes to their PDF page', () => {
		const r = parseLatexLog('Overfull \\hbox (3.0pt too wide) has occurred while \\output is active [7]');
		expect(r.badboxes[0]?.page).toBe(7);
		expect(r.badboxes[0]?.line).toBeUndefined();
	});

	it("suppresses the empty `thebibliography' environment noise", () => {
		const r = parseLatexLog("LaTeX Warning: Empty `thebibliography' environment on input line 8.\n");
		expect(r.warnings).toHaveLength(0);
	});
});
