<script lang="ts">
	// The Overleaf alternatives page. English only, like the docs: a comparison has to be checked
	// again whenever one of the other editors changes, and one copy is enough to keep true. Every
	// claim about another editor comes from that project's own site, and the date at the bottom
	// says when they were last checked.
	import ArrowRight from '@lucide/svelte/icons/arrow-right';
	import Download from '@lucide/svelte/icons/download';
	import { m } from '$lib/paraglide/messages';

	const URL = 'https://texpile.com/overleaf-alternatives';
	const TITLE = 'Overleaf alternatives that run on your computer - Texpile';
	const DESCRIPTION =
		'Five free LaTeX editors to use instead of Overleaf, with what each one has: visual editing, live preview, collaboration, Typst, and what it needs installed.';
	const CHECKED = 'September 2026';

	type Editor = {
		name: string;
		url: string;
		visual: string;
		preview: string;
		collab: string;
		typst: string;
		license: string;
		needs: string;
		about: string;
	};

	const EDITORS: Editor[] = [
		{
			name: 'Texpile',
			url: '/download',
			visual: 'Yes, on the .tex file itself',
			preview: 'As you type, with your own lualatex',
			collab: 'Yes, end to end encrypted, no account',
			typst: 'Yes',
			license: 'AGPL-3.0',
			needs: 'A TeX distribution',
			about:
				'Texpile edits the same .tex file visually or in source and saves it back with nothing changed but your edits. The live preview re-typesets the page as you type with your own lualatex. A shared session lets other people edit the folder with you in real time, end to end encrypted, and a guest needs no TeX installed because the host compiles. It also edits Typst and Markdown. It is the youngest editor on this list, and it needs a TeX distribution installed before it can compile.'
		},
		{
			name: 'TeXstudio',
			url: 'https://www.texstudio.org/',
			visual: 'No',
			preview: 'Formulas inline; PDF viewer with SyncTeX',
			collab: 'Since 4.9, with teamtype, on macOS and Linux',
			typst: 'No',
			license: 'GPL-2.0',
			needs: 'A TeX distribution',
			about:
				'TeXstudio is a source editor with syntax highlighting, completion, multiple cursors, an integrated PDF viewer with word-level syncing, and an inline preview of formulas and code segments. Since version 4.9 it offers collaborative editing through teamtype, on macOS and Linux.'
		},
		{
			name: 'Texmaker',
			url: 'https://www.xm1math.net/texmaker/',
			visual: 'No',
			preview: 'PDF viewer with continuous view and SyncTeX',
			collab: 'No',
			typst: 'No',
			license: 'GPL',
			needs: 'A TeX distribution',
			about:
				'Texmaker is a single-window LaTeX editor with a built-in PDF viewer, SyncTeX, code completion, spell check as you type, a structure view, and a panel of mathematical symbols. It has no visual mode and no collaboration.'
		},
		{
			name: 'LyX',
			url: 'https://www.lyx.org/',
			visual: 'Structure-based (WYSIWYM), in its own .lyx format',
			preview: 'Math and figures inline; PDF on export',
			collab: 'No',
			typst: 'No',
			license: 'GPL-2.0',
			needs: 'A TeX distribution',
			about:
				'LyX takes a different route. You write against the structure of the document, with an integrated equation editor, and LyX generates the LaTeX. Documents are kept in its own .lyx format, so an existing .tex file has to be imported, and the LaTeX it exports is generated by LyX.'
		},
		{
			name: 'VS Code with LaTeX Workshop',
			url: 'https://github.com/James-Yu/LaTeX-Workshop',
			visual: 'No',
			preview: 'PDF viewer refreshed on build, with SyncTeX',
			collab: 'With the Live Share extension',
			typst: 'With the Tinymist extension',
			license: 'MIT',
			needs: 'VS Code and a TeX distribution',
			about:
				'For anyone already writing in VS Code, LaTeX Workshop adds building on save, a PDF viewer with SyncTeX, completion for citations, references, commands, and environments, and parsed build errors. Collaboration comes from the Live Share extension and Typst from the Tinymist extension, each a separate install.'
		}
	];

	const COLUMNS: { key: keyof Editor; label: string }[] = [
		{ key: 'visual', label: 'Visual editing' },
		{ key: 'preview', label: 'Live preview' },
		{ key: 'collab', label: 'Collaboration' },
		{ key: 'typst', label: 'Typst' },
		{ key: 'license', label: 'License' },
		{ key: 'needs', label: 'Needs' }
	];
</script>

<svelte:head>
	<title>{TITLE}</title>
	<meta name="description" content={DESCRIPTION} />

	<meta property="og:url" content={URL} />
	<meta property="og:title" content={TITLE} />
	<meta property="og:description" content={DESCRIPTION} />

	<meta property="twitter:url" content={URL} />
	<meta property="twitter:title" content={TITLE} />
	<meta property="twitter:description" content={DESCRIPTION} />

	<!-- one English page under every locale prefix, so the English URL is canonical for all of them -->
	<link rel="canonical" href={URL} />
</svelte:head>

<section class="bg-surface-50 border-surface-200 border-b">
	<div class="container mx-auto max-w-3xl px-4 py-14 sm:px-6 md:py-16 lg:px-8">
		<h1 class="text-surface-900 text-3xl font-bold md:text-4xl">Overleaf alternatives</h1>
		<p class="text-surface-600 mt-4 text-lg leading-relaxed">
			Overleaf runs in the browser, with a 10 second compile limit and one collaborator per project on the free plan. The editors below run
			on your own computer with a TeX distribution installed, so nothing is uploaded and a compile takes as long as it takes. All five are
			free and run on Windows, macOS, and Linux.
		</p>
		<p class="text-surface-600 mt-4 leading-relaxed">
			We built Texpile to be a direct offline replacement for Overleaf. We are the makers of Texpile, so we may be biased towards our own
			editor.
		</p>
	</div>
</section>

<section class="bg-white py-12 md:py-16">
	<div class="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<div class="border-surface-200 overflow-x-auto rounded-lg border">
			<table class="w-full min-w-3xl text-left text-sm">
				<thead class="bg-surface-50 text-surface-700">
					<tr>
						<th scope="col" class="px-4 py-3 font-semibold">Editor</th>
						{#each COLUMNS as c (c.key)}
							<th scope="col" class="px-4 py-3 font-semibold">{c.label}</th>
						{/each}
					</tr>
				</thead>
				<tbody class="text-surface-700">
					{#each EDITORS as e (e.name)}
						<tr class="border-surface-200 border-t">
							<th scope="row" class="text-surface-900 px-4 py-3 align-top font-semibold whitespace-nowrap">{e.name}</th>
							{#each COLUMNS as c (c.key)}
								<td class="px-4 py-3 align-top">{e[c.key]}</td>
							{/each}
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</div>
</section>

<section class="border-surface-200 border-t bg-white py-12 md:py-16">
	<div class="container mx-auto max-w-3xl space-y-12 px-4 sm:px-6 lg:px-8">
		<div class="space-y-10">
			<h2 class="text-surface-900 text-2xl font-semibold">The editors</h2>
			{#each EDITORS as e (e.name)}
				<div>
					<h3 class="text-surface-900 text-xl font-semibold">
						{#if e.url.startsWith('/')}
							<a href={e.url} class="hover:text-primary-600">{e.name}</a>
						{:else}
							<a href={e.url} target="_blank" rel="noopener noreferrer" class="hover:text-primary-600">{e.name}</a>
						{/if}
					</h3>
					<p class="text-surface-600 mt-3 leading-relaxed">{e.about}</p>
				</div>
			{/each}
		</div>

		<div>
			<h2 class="text-surface-900 text-2xl font-semibold">What Overleaf keeps</h2>
			<p class="text-surface-600 mt-3 leading-relaxed">
				Overleaf needs nothing installed, has a template gallery, and offers track changes on paid plans. Every editor above needs a TeX
				distribution on your computer first, and that install is the main cost of leaving.
			</p>
		</div>

		<div>
			<h2 class="text-surface-900 text-2xl font-semibold">Which one</h2>
			<ul class="text-surface-600 mt-3 space-y-2 leading-relaxed">
				<li>A visual editor over real .tex files, with collaboration: Texpile.</li>
				<li>A source editor with a built-in PDF viewer: TeXstudio, or Texmaker for a simpler one.</li>
				<li>Already writing in VS Code: LaTeX Workshop.</li>
				<li>Writing against the structure of a document, with the LaTeX generated for you: LyX.</li>
			</ul>
		</div>

		<p class="text-surface-600 leading-relaxed">
			Head to head: <a href="/vs/texstudio" class="text-primary-600 hover:text-primary-700">Texpile vs TeXstudio</a>,
			<a href="/vs/lyx" class="text-primary-600 hover:text-primary-700">Texpile vs LyX</a>,
			<a href="/vs/overleaf" class="text-primary-600 hover:text-primary-700">Texpile vs Overleaf</a>, and
			<a href="/vs/latex-workshop" class="text-primary-600 hover:text-primary-700">Texpile vs LaTeX Workshop</a>.
		</p>

		<p class="text-surface-500 text-sm">
			Checked {CHECKED} against each project's own site. Corrections are welcome as an
			<a href="https://github.com/texpile/texpile/issues" target="_blank" rel="noopener noreferrer" class="underline hover:text-surface-700"
				>issue on GitHub</a
			>.
		</p>

		<div class="flex flex-wrap items-center gap-4">
			<a
				href="/download"
				class="btn preset-filled-primary-500 rounded-base inline-flex items-center gap-2 px-6 py-2.5 font-semibold text-white"
			>
				<Download class="h-5 w-5" />
				{m.notfound_download()}
			</a>
			<a
				href="/latex-editor"
				class="text-primary-600 hover:text-primary-700 inline-flex items-center gap-1.5 font-medium transition-colors"
			>
				{m.footer_latex()}
				<ArrowRight class="h-4 w-4" />
			</a>
		</div>
	</div>
</section>
