// GENERATED by scripts/gen-bib-datamodel.mjs - do not edit by hand.
//
// biblatex's own data model, read from the files Biber reads: which entry types exist, which
// fields each accepts, what each field holds, which are mandatory, and the legacy BibTeX names
// biblatex renames. Regenerate when biblatex updates.
//
// Source: biblatex 3.21 (2025/07/10)

/** a field holds one value, or a list of them (authors, locations) */
export type BibFieldKind = 'field' | 'list';

export type BibFieldSpec = { kind: BibFieldKind; datatype: string };

/** one mandatory-field rule: all of them, exactly one of them, or at least one of them */
export type BibConstraint = { all?: string[]; xor?: string[]; or?: string[] };

export const BIBLATEX_VERSION = '3.21 (2025/07/10)';

/** every entry type biblatex defines, `customa`-`customf` and the machinery types included */
export const BIB_ENTRY_TYPES: readonly string[] = [
	'article',
	'artwork',
	'audio',
	'bibnote',
	'book',
	'bookinbook',
	'booklet',
	'collection',
	'commentary',
	'customa',
	'customb',
	'customc',
	'customd',
	'custome',
	'customf',
	'dataset',
	'image',
	'inbook',
	'incollection',
	'inproceedings',
	'inreference',
	'jurisdiction',
	'legal',
	'legislation',
	'letter',
	'manual',
	'misc',
	'movie',
	'music',
	'mvbook',
	'mvcollection',
	'mvproceedings',
	'mvreference',
	'online',
	'patent',
	'performance',
	'periodical',
	'proceedings',
	'reference',
	'report',
	'review',
	'set',
	'software',
	'standard',
	'suppbook',
	'suppcollection',
	'suppperiodical',
	'thesis',
	'unpublished',
	'video',
	'xdata'
];

/** what each field name holds */
export const BIB_FIELDS: Readonly<Record<string, BibFieldSpec>> = {
	abstract: {
		kind: 'field',
		datatype: 'literal'
	},
	addendum: {
		kind: 'field',
		datatype: 'literal'
	},
	afterword: {
		kind: 'list',
		datatype: 'name'
	},
	annotation: {
		kind: 'field',
		datatype: 'literal'
	},
	annotator: {
		kind: 'list',
		datatype: 'name'
	},
	author: {
		kind: 'list',
		datatype: 'name'
	},
	authortype: {
		kind: 'field',
		datatype: 'key'
	},
	bookauthor: {
		kind: 'list',
		datatype: 'name'
	},
	bookpagination: {
		kind: 'field',
		datatype: 'key'
	},
	booksubtitle: {
		kind: 'field',
		datatype: 'literal'
	},
	booktitle: {
		kind: 'field',
		datatype: 'literal'
	},
	booktitleaddon: {
		kind: 'field',
		datatype: 'literal'
	},
	chapter: {
		kind: 'field',
		datatype: 'literal'
	},
	commentator: {
		kind: 'list',
		datatype: 'name'
	},
	crossref: {
		kind: 'field',
		datatype: 'entrykey'
	},
	date: {
		kind: 'field',
		datatype: 'date'
	},
	day: {
		kind: 'field',
		datatype: 'datepart'
	},
	doi: {
		kind: 'field',
		datatype: 'verbatim'
	},
	edition: {
		kind: 'field',
		datatype: 'literal'
	},
	editor: {
		kind: 'list',
		datatype: 'name'
	},
	editora: {
		kind: 'list',
		datatype: 'name'
	},
	editoratype: {
		kind: 'field',
		datatype: 'key'
	},
	editorb: {
		kind: 'list',
		datatype: 'name'
	},
	editorbtype: {
		kind: 'field',
		datatype: 'key'
	},
	editorc: {
		kind: 'list',
		datatype: 'name'
	},
	editorctype: {
		kind: 'field',
		datatype: 'key'
	},
	editortype: {
		kind: 'field',
		datatype: 'key'
	},
	eid: {
		kind: 'field',
		datatype: 'literal'
	},
	endday: {
		kind: 'field',
		datatype: 'datepart'
	},
	endhour: {
		kind: 'field',
		datatype: 'datepart'
	},
	endminute: {
		kind: 'field',
		datatype: 'datepart'
	},
	endmonth: {
		kind: 'field',
		datatype: 'datepart'
	},
	endsecond: {
		kind: 'field',
		datatype: 'datepart'
	},
	endtimezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	endyear: {
		kind: 'field',
		datatype: 'datepart'
	},
	endyeardivision: {
		kind: 'field',
		datatype: 'datepart'
	},
	entryset: {
		kind: 'field',
		datatype: 'entrykey'
	},
	entrysubtype: {
		kind: 'field',
		datatype: 'literal'
	},
	eprint: {
		kind: 'field',
		datatype: 'verbatim'
	},
	eprintclass: {
		kind: 'field',
		datatype: 'literal'
	},
	eprinttype: {
		kind: 'field',
		datatype: 'literal'
	},
	eventdate: {
		kind: 'field',
		datatype: 'date'
	},
	eventday: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendday: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendhour: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendminute: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendmonth: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendsecond: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendtimezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendyear: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventendyeardivision: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventhour: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventminute: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventmonth: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventsecond: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventtimezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventtitle: {
		kind: 'field',
		datatype: 'literal'
	},
	eventtitleaddon: {
		kind: 'field',
		datatype: 'literal'
	},
	eventyear: {
		kind: 'field',
		datatype: 'datepart'
	},
	eventyeardivision: {
		kind: 'field',
		datatype: 'datepart'
	},
	execute: {
		kind: 'field',
		datatype: 'code'
	},
	file: {
		kind: 'field',
		datatype: 'verbatim'
	},
	foreword: {
		kind: 'list',
		datatype: 'name'
	},
	gender: {
		kind: 'field',
		datatype: 'literal'
	},
	holder: {
		kind: 'list',
		datatype: 'name'
	},
	hour: {
		kind: 'field',
		datatype: 'datepart'
	},
	howpublished: {
		kind: 'field',
		datatype: 'literal'
	},
	ids: {
		kind: 'field',
		datatype: 'entrykey'
	},
	indexsorttitle: {
		kind: 'field',
		datatype: 'literal'
	},
	indextitle: {
		kind: 'field',
		datatype: 'literal'
	},
	institution: {
		kind: 'list',
		datatype: 'literal'
	},
	introduction: {
		kind: 'list',
		datatype: 'name'
	},
	isan: {
		kind: 'field',
		datatype: 'literal'
	},
	isbn: {
		kind: 'field',
		datatype: 'literal'
	},
	ismn: {
		kind: 'field',
		datatype: 'literal'
	},
	isrn: {
		kind: 'field',
		datatype: 'literal'
	},
	issn: {
		kind: 'field',
		datatype: 'literal'
	},
	issue: {
		kind: 'field',
		datatype: 'literal'
	},
	issuesubtitle: {
		kind: 'field',
		datatype: 'literal'
	},
	issuetitle: {
		kind: 'field',
		datatype: 'literal'
	},
	issuetitleaddon: {
		kind: 'field',
		datatype: 'literal'
	},
	iswc: {
		kind: 'field',
		datatype: 'literal'
	},
	journalsubtitle: {
		kind: 'field',
		datatype: 'literal'
	},
	journaltitle: {
		kind: 'field',
		datatype: 'literal'
	},
	journaltitleaddon: {
		kind: 'field',
		datatype: 'literal'
	},
	keywords: {
		kind: 'field',
		datatype: 'keyword'
	},
	label: {
		kind: 'field',
		datatype: 'literal'
	},
	langid: {
		kind: 'field',
		datatype: 'literal'
	},
	langidopts: {
		kind: 'field',
		datatype: 'literal'
	},
	language: {
		kind: 'list',
		datatype: 'key'
	},
	library: {
		kind: 'field',
		datatype: 'literal'
	},
	lista: {
		kind: 'list',
		datatype: 'literal'
	},
	listb: {
		kind: 'list',
		datatype: 'literal'
	},
	listc: {
		kind: 'list',
		datatype: 'literal'
	},
	listd: {
		kind: 'list',
		datatype: 'literal'
	},
	liste: {
		kind: 'list',
		datatype: 'literal'
	},
	listf: {
		kind: 'list',
		datatype: 'literal'
	},
	location: {
		kind: 'list',
		datatype: 'literal'
	},
	mainsubtitle: {
		kind: 'field',
		datatype: 'literal'
	},
	maintitle: {
		kind: 'field',
		datatype: 'literal'
	},
	maintitleaddon: {
		kind: 'field',
		datatype: 'literal'
	},
	minute: {
		kind: 'field',
		datatype: 'datepart'
	},
	month: {
		kind: 'field',
		datatype: 'datepart'
	},
	namea: {
		kind: 'list',
		datatype: 'name'
	},
	nameaddon: {
		kind: 'field',
		datatype: 'literal'
	},
	nameatype: {
		kind: 'field',
		datatype: 'key'
	},
	nameb: {
		kind: 'list',
		datatype: 'name'
	},
	namebtype: {
		kind: 'field',
		datatype: 'key'
	},
	namec: {
		kind: 'list',
		datatype: 'name'
	},
	namectype: {
		kind: 'field',
		datatype: 'key'
	},
	note: {
		kind: 'field',
		datatype: 'literal'
	},
	number: {
		kind: 'field',
		datatype: 'literal'
	},
	options: {
		kind: 'field',
		datatype: 'option'
	},
	organization: {
		kind: 'list',
		datatype: 'literal'
	},
	origdate: {
		kind: 'field',
		datatype: 'date'
	},
	origday: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendday: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendhour: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendminute: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendmonth: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendsecond: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendtimezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendyear: {
		kind: 'field',
		datatype: 'datepart'
	},
	origendyeardivision: {
		kind: 'field',
		datatype: 'datepart'
	},
	orighour: {
		kind: 'field',
		datatype: 'datepart'
	},
	origlanguage: {
		kind: 'list',
		datatype: 'key'
	},
	origlocation: {
		kind: 'list',
		datatype: 'literal'
	},
	origminute: {
		kind: 'field',
		datatype: 'datepart'
	},
	origmonth: {
		kind: 'field',
		datatype: 'datepart'
	},
	origpublisher: {
		kind: 'list',
		datatype: 'literal'
	},
	origsecond: {
		kind: 'field',
		datatype: 'datepart'
	},
	origtimezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	origtitle: {
		kind: 'field',
		datatype: 'literal'
	},
	origyear: {
		kind: 'field',
		datatype: 'datepart'
	},
	origyeardivision: {
		kind: 'field',
		datatype: 'datepart'
	},
	pages: {
		kind: 'field',
		datatype: 'range'
	},
	pagetotal: {
		kind: 'field',
		datatype: 'literal'
	},
	pagination: {
		kind: 'field',
		datatype: 'key'
	},
	part: {
		kind: 'field',
		datatype: 'literal'
	},
	presort: {
		kind: 'field',
		datatype: 'literal'
	},
	publisher: {
		kind: 'list',
		datatype: 'literal'
	},
	pubstate: {
		kind: 'field',
		datatype: 'key'
	},
	related: {
		kind: 'field',
		datatype: 'entrykey'
	},
	relatedoptions: {
		kind: 'field',
		datatype: 'option'
	},
	relatedstring: {
		kind: 'field',
		datatype: 'literal'
	},
	relatedtype: {
		kind: 'field',
		datatype: 'literal'
	},
	reprinttitle: {
		kind: 'field',
		datatype: 'literal'
	},
	second: {
		kind: 'field',
		datatype: 'datepart'
	},
	series: {
		kind: 'field',
		datatype: 'literal'
	},
	shortauthor: {
		kind: 'list',
		datatype: 'name'
	},
	shorteditor: {
		kind: 'list',
		datatype: 'name'
	},
	shorthand: {
		kind: 'field',
		datatype: 'literal'
	},
	shorthandintro: {
		kind: 'field',
		datatype: 'literal'
	},
	shortjournal: {
		kind: 'field',
		datatype: 'literal'
	},
	shortseries: {
		kind: 'field',
		datatype: 'literal'
	},
	shorttitle: {
		kind: 'field',
		datatype: 'literal'
	},
	sortkey: {
		kind: 'field',
		datatype: 'literal'
	},
	sortname: {
		kind: 'list',
		datatype: 'name'
	},
	sortshorthand: {
		kind: 'field',
		datatype: 'literal'
	},
	sorttitle: {
		kind: 'field',
		datatype: 'literal'
	},
	sortyear: {
		kind: 'field',
		datatype: 'integer'
	},
	subtitle: {
		kind: 'field',
		datatype: 'literal'
	},
	timezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	title: {
		kind: 'field',
		datatype: 'literal'
	},
	titleaddon: {
		kind: 'field',
		datatype: 'literal'
	},
	translator: {
		kind: 'list',
		datatype: 'name'
	},
	type: {
		kind: 'field',
		datatype: 'key'
	},
	url: {
		kind: 'field',
		datatype: 'uri'
	},
	urldate: {
		kind: 'field',
		datatype: 'date'
	},
	urlday: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendday: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendhour: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendminute: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendmonth: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendsecond: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendtimezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendyear: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlendyeardivision: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlhour: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlminute: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlmonth: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlsecond: {
		kind: 'field',
		datatype: 'datepart'
	},
	urltimezone: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlyear: {
		kind: 'field',
		datatype: 'datepart'
	},
	urlyeardivision: {
		kind: 'field',
		datatype: 'datepart'
	},
	usera: {
		kind: 'field',
		datatype: 'literal'
	},
	userb: {
		kind: 'field',
		datatype: 'literal'
	},
	userc: {
		kind: 'field',
		datatype: 'literal'
	},
	userd: {
		kind: 'field',
		datatype: 'literal'
	},
	usere: {
		kind: 'field',
		datatype: 'literal'
	},
	userf: {
		kind: 'field',
		datatype: 'literal'
	},
	venue: {
		kind: 'field',
		datatype: 'literal'
	},
	verba: {
		kind: 'field',
		datatype: 'verbatim'
	},
	verbb: {
		kind: 'field',
		datatype: 'verbatim'
	},
	verbc: {
		kind: 'field',
		datatype: 'verbatim'
	},
	version: {
		kind: 'field',
		datatype: 'literal'
	},
	volume: {
		kind: 'field',
		datatype: 'integer'
	},
	volumes: {
		kind: 'field',
		datatype: 'integer'
	},
	xdata: {
		kind: 'field',
		datatype: 'entrykey'
	},
	xref: {
		kind: 'field',
		datatype: 'entrykey'
	},
	year: {
		kind: 'field',
		datatype: 'datepart'
	},
	yeardivision: {
		kind: 'field',
		datatype: 'datepart'
	}
};

/** accepted by every entry type */
export const BIB_UNIVERSAL_FIELDS: readonly string[] = [
	'abstract',
	'annotation',
	'authortype',
	'bookpagination',
	'crossref',
	'date',
	'day',
	'doi',
	'endday',
	'endhour',
	'endminute',
	'endmonth',
	'endsecond',
	'endtimezone',
	'endyear',
	'endyeardivision',
	'entryset',
	'entrysubtype',
	'eprint',
	'eprintclass',
	'eprinttype',
	'execute',
	'file',
	'gender',
	'hour',
	'ids',
	'indexsorttitle',
	'indextitle',
	'isan',
	'ismn',
	'iswc',
	'keywords',
	'label',
	'langid',
	'langidopts',
	'library',
	'lista',
	'listb',
	'listc',
	'listd',
	'liste',
	'listf',
	'minute',
	'month',
	'namea',
	'nameaddon',
	'nameatype',
	'nameb',
	'namebtype',
	'namec',
	'namectype',
	'options',
	'origdate',
	'origday',
	'origendday',
	'origendhour',
	'origendminute',
	'origendmonth',
	'origendsecond',
	'origendtimezone',
	'origendyear',
	'origendyeardivision',
	'orighour',
	'origlocation',
	'origminute',
	'origmonth',
	'origpublisher',
	'origsecond',
	'origtimezone',
	'origtitle',
	'origyear',
	'origyeardivision',
	'pagination',
	'presort',
	'related',
	'relatedoptions',
	'relatedstring',
	'relatedtype',
	'second',
	'shortauthor',
	'shorteditor',
	'shorthand',
	'shorthandintro',
	'shortjournal',
	'shortseries',
	'shorttitle',
	'sortkey',
	'sortname',
	'sortshorthand',
	'sorttitle',
	'sortyear',
	'timezone',
	'url',
	'urldate',
	'urlday',
	'urlendday',
	'urlendhour',
	'urlendminute',
	'urlendmonth',
	'urlendsecond',
	'urlendtimezone',
	'urlendyear',
	'urlendyeardivision',
	'urlhour',
	'urlminute',
	'urlmonth',
	'urlsecond',
	'urltimezone',
	'urlyear',
	'urlyeardivision',
	'usera',
	'userb',
	'userc',
	'userd',
	'usere',
	'userf',
	'verba',
	'verbb',
	'verbc',
	'xdata',
	'xref',
	'year',
	'yeardivision'
];

/** accepted by that entry type on top of the universal ones */
export const BIB_FIELDS_BY_TYPE: Readonly<Record<string, readonly string[]>> = {
	article: [
		'addendum',
		'annotator',
		'author',
		'commentator',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'issn',
		'issue',
		'issuesubtitle',
		'issuetitle',
		'issuetitleaddon',
		'journalsubtitle',
		'journaltitle',
		'journaltitleaddon',
		'language',
		'note',
		'number',
		'origlanguage',
		'pages',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'version',
		'volume'
	],
	bibnote: ['note'],
	book: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'pagetotal',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	bookinbook: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'bookauthor',
		'booksubtitle',
		'booktitle',
		'booktitleaddon',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	booklet: [
		'addendum',
		'author',
		'chapter',
		'editor',
		'editortype',
		'eid',
		'howpublished',
		'language',
		'location',
		'note',
		'pages',
		'pagetotal',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'type'
	],
	collection: [
		'addendum',
		'afterword',
		'annotator',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'pagetotal',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	dataset: [
		'addendum',
		'author',
		'edition',
		'editor',
		'editortype',
		'language',
		'location',
		'note',
		'number',
		'organization',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'type',
		'version'
	],
	inbook: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'bookauthor',
		'booksubtitle',
		'booktitle',
		'booktitleaddon',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	incollection: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'booksubtitle',
		'booktitle',
		'booktitleaddon',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	inproceedings: [
		'addendum',
		'author',
		'booksubtitle',
		'booktitle',
		'booktitleaddon',
		'chapter',
		'editor',
		'editortype',
		'eid',
		'eventdate',
		'eventday',
		'eventendday',
		'eventendhour',
		'eventendminute',
		'eventendmonth',
		'eventendsecond',
		'eventendtimezone',
		'eventendyear',
		'eventendyeardivision',
		'eventhour',
		'eventminute',
		'eventmonth',
		'eventsecond',
		'eventtimezone',
		'eventtitle',
		'eventtitleaddon',
		'eventyear',
		'eventyeardivision',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'organization',
		'pages',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'venue',
		'volume',
		'volumes'
	],
	inreference: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'booksubtitle',
		'booktitle',
		'booktitleaddon',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	manual: [
		'addendum',
		'author',
		'chapter',
		'edition',
		'editor',
		'editortype',
		'eid',
		'isbn',
		'language',
		'location',
		'note',
		'number',
		'organization',
		'pages',
		'pagetotal',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'type',
		'version'
	],
	misc: [
		'addendum',
		'author',
		'editor',
		'editortype',
		'howpublished',
		'language',
		'location',
		'note',
		'organization',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'type',
		'version'
	],
	mvbook: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'note',
		'number',
		'origlanguage',
		'pagetotal',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	mvcollection: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'note',
		'number',
		'origlanguage',
		'publisher',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	mvproceedings: [
		'addendum',
		'editor',
		'editortype',
		'eventdate',
		'eventday',
		'eventendday',
		'eventendhour',
		'eventendminute',
		'eventendmonth',
		'eventendsecond',
		'eventendtimezone',
		'eventendyear',
		'eventendyeardivision',
		'eventhour',
		'eventminute',
		'eventmonth',
		'eventsecond',
		'eventtimezone',
		'eventtitle',
		'eventtitleaddon',
		'eventyear',
		'eventyeardivision',
		'isbn',
		'language',
		'location',
		'note',
		'number',
		'organization',
		'pagetotal',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'venue',
		'volumes'
	],
	mvreference: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'note',
		'number',
		'origlanguage',
		'publisher',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	online: [
		'addendum',
		'author',
		'editor',
		'editortype',
		'language',
		'note',
		'organization',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'version'
	],
	patent: ['addendum', 'author', 'holder', 'location', 'note', 'number', 'pubstate', 'subtitle', 'title', 'titleaddon', 'type', 'version'],
	periodical: [
		'addendum',
		'date',
		'day',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'endday',
		'endhour',
		'endminute',
		'endmonth',
		'endsecond',
		'endtimezone',
		'endyear',
		'endyeardivision',
		'hour',
		'issn',
		'issue',
		'issuesubtitle',
		'issuetitle',
		'issuetitleaddon',
		'language',
		'minute',
		'month',
		'note',
		'number',
		'pubstate',
		'second',
		'series',
		'subtitle',
		'timezone',
		'title',
		'titleaddon',
		'volume',
		'year',
		'yeardivision'
	],
	proceedings: [
		'addendum',
		'chapter',
		'editor',
		'editortype',
		'eid',
		'eventdate',
		'eventday',
		'eventendday',
		'eventendhour',
		'eventendminute',
		'eventendmonth',
		'eventendsecond',
		'eventendtimezone',
		'eventendyear',
		'eventendyeardivision',
		'eventhour',
		'eventminute',
		'eventmonth',
		'eventsecond',
		'eventtimezone',
		'eventtitle',
		'eventtitleaddon',
		'eventyear',
		'eventyeardivision',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'organization',
		'pages',
		'pagetotal',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'venue',
		'volume',
		'volumes'
	],
	reference: [
		'addendum',
		'afterword',
		'annotator',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'pagetotal',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	report: [
		'addendum',
		'author',
		'chapter',
		'eid',
		'institution',
		'isrn',
		'language',
		'location',
		'note',
		'number',
		'pages',
		'pagetotal',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'type',
		'version'
	],
	set: ['entryset'],
	software: [
		'addendum',
		'author',
		'editor',
		'editortype',
		'howpublished',
		'language',
		'location',
		'note',
		'organization',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'type',
		'version'
	],
	suppbook: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'bookauthor',
		'booksubtitle',
		'booktitle',
		'booktitleaddon',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	suppcollection: [
		'addendum',
		'afterword',
		'annotator',
		'author',
		'booksubtitle',
		'booktitle',
		'booktitleaddon',
		'chapter',
		'commentator',
		'edition',
		'editor',
		'editora',
		'editoratype',
		'editorb',
		'editorbtype',
		'editorc',
		'editorctype',
		'editortype',
		'eid',
		'foreword',
		'introduction',
		'isbn',
		'language',
		'location',
		'mainsubtitle',
		'maintitle',
		'maintitleaddon',
		'note',
		'number',
		'origlanguage',
		'pages',
		'part',
		'publisher',
		'pubstate',
		'series',
		'subtitle',
		'title',
		'titleaddon',
		'translator',
		'volume',
		'volumes'
	],
	thesis: [
		'addendum',
		'author',
		'chapter',
		'eid',
		'institution',
		'language',
		'location',
		'note',
		'pages',
		'pagetotal',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'type'
	],
	unpublished: [
		'addendum',
		'author',
		'eventdate',
		'eventday',
		'eventendday',
		'eventendhour',
		'eventendminute',
		'eventendmonth',
		'eventendsecond',
		'eventendtimezone',
		'eventendyear',
		'eventendyeardivision',
		'eventhour',
		'eventminute',
		'eventmonth',
		'eventsecond',
		'eventtimezone',
		'eventtitle',
		'eventtitleaddon',
		'eventyear',
		'eventyeardivision',
		'howpublished',
		'language',
		'location',
		'note',
		'pubstate',
		'subtitle',
		'title',
		'titleaddon',
		'type',
		'venue'
	]
};

/** what an entry of that type must carry, as biber will check it */
export const BIB_MANDATORY: Readonly<Record<string, readonly BibConstraint[]>> = {
	article: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'journaltitle', 'title']
		}
	],
	book: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title']
		}
	],
	inbook: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title', 'booktitle']
		}
	],
	bookinbook: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title', 'booktitle']
		}
	],
	suppbook: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title', 'booktitle']
		}
	],
	booklet: [
		{
			xor: ['date', 'year']
		},
		{
			or: ['author', 'editor']
		},
		{
			all: ['title']
		}
	],
	collection: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['editor', 'title']
		}
	],
	incollection: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'editor', 'title', 'booktitle']
		}
	],
	suppcollection: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'editor', 'title', 'booktitle']
		}
	],
	manual: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['title']
		}
	],
	misc: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['title']
		}
	],
	mvbook: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title']
		}
	],
	mvcollection: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['editor', 'title']
		}
	],
	online: [
		{
			xor: ['date', 'year']
		},
		{
			or: ['url', 'doi', 'eprint']
		},
		{
			all: ['title']
		}
	],
	patent: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title', 'number']
		}
	],
	periodical: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['editor', 'title']
		}
	],
	suppperiodical: [
		{
			xor: ['date', 'year']
		}
	],
	proceedings: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['title']
		}
	],
	inproceedings: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title', 'booktitle']
		}
	],
	reference: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['editor', 'title']
		}
	],
	inreference: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'editor', 'title', 'booktitle']
		}
	],
	report: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title', 'type', 'institution']
		}
	],
	set: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['entryset']
		}
	],
	thesis: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title', 'type', 'institution']
		}
	],
	unpublished: [
		{
			xor: ['date', 'year']
		},
		{
			all: ['author', 'title']
		}
	],
	mvreference: [
		{
			all: ['editor', 'title']
		}
	],
	dataset: [
		{
			all: ['title']
		}
	],
	software: [
		{
			all: ['title']
		}
	],
	mvproceedings: [
		{
			all: ['title']
		}
	]
};

/** legacy BibTeX field names biblatex renames on input: `journal` is `journaltitle` */
export const BIB_FIELD_ALIASES: Readonly<Record<string, string>> = {
	hyphenation: 'langid',
	address: 'location',
	school: 'institution',
	annote: 'annotation',
	archiveprefix: 'eprinttype',
	journal: 'journaltitle',
	primaryclass: 'eprintclass',
	key: 'sortkey',
	pdf: 'file'
};
