// The icons a page's front matter can name. An explicit map, because a namespace import of
// @lucide/svelte cannot be tree-shaken and would ship every icon.
import {
	BookMarked,
	Bot,
	BoxSelect,
	Code,
	Eye,
	Files,
	FileText,
	GitBranch,
	HardDriveDownload,
	Image,
	Keyboard,
	Layers,
	Library,
	MessageSquare,
	Palette,
	PenLine,
	Play,
	Plug,
	Rocket,
	Settings,
	Sigma,
	Sparkles,
	SpellCheck,
	Table,
	Type,
	Users,
	type Icon
} from '@lucide/svelte';

export const ICONS: Record<string, typeof Icon> = {
	'book-marked': BookMarked,
	bot: Bot,
	'box-select': BoxSelect,
	code: Code,
	eye: Eye,
	files: Files,
	'file-text': FileText,
	'git-branch': GitBranch,
	'hard-drive-download': HardDriveDownload,
	image: Image,
	keyboard: Keyboard,
	layers: Layers,
	library: Library,
	'message-square': MessageSquare,
	palette: Palette,
	'pen-line': PenLine,
	play: Play,
	plug: Plug,
	rocket: Rocket,
	settings: Settings,
	sigma: Sigma,
	sparkles: Sparkles,
	'spell-check': SpellCheck,
	table: Table,
	type: Type,
	users: Users
};
