// GENERATED by scripts/gen-latex-symbols.mjs - do not edit by hand.
//
// Source: Detexify 196daf1 (https://github.com/kirel/detexify), MIT, see DETEXIFY-LICENSE.txt
// beside this file

export type LatexSymbolGroup =
	'letters' | 'operators' | 'relations' | 'arrows' | 'delimiters' | 'punctuation' | 'phonetic' | 'other' | 'signs';

export const LATEX_SYMBOL_GROUPS: readonly LatexSymbolGroup[] = [
	'letters',
	'operators',
	'relations',
	'arrows',
	'delimiters',
	'punctuation',
	'phonetic',
	'other',
	'signs'
];

/** the size of latexSymbols.png, which every row's rectangle is measured in, and the height Detexify fits each drawing to */
export const LATEX_SYMBOL_SHEET = { width: 1212, height: 1184, boxHeight: 40 };
